export const CREATE_SHEET = { CREATE_SHEET : 'CREATE_SHEET', CHANGE_SHEETDIV : "CHANGE_SHEETDIV" };

export const CREATE_SAMPLE = { CREATE_SAMPLE : 'CREATE_SAMPLE'};

export const REMOVE_SAMPLE = { REMOVE_SAMPLE : 'REMOVE_SAMPLE'};

export const CHANGE_SAMPLE = { CHANGE_SAMPLE : 'CHANGE_SAMPLE', CHANGE_DATA : 'CHANGE_DATA', CHANGE_TEMP : 'CHANGE_TEMP'};

export const SUBSUM_SAMPLE = { SUBSUM : 'SUBSUM', CUMULATE : 'CUMULATE'};